In [2]:
import pandas as pd

In [3]:
govdata = pd.read_excel(r'C:\Users\wc145\Desktop\fiscal-year-2015.xlsx',sheet_name='FY15_HR')

In [13]:
da = pd.DataFrame(govdata,columns=['TEMPORARY_EMPLOYEE_ID','EMPL_NM'])

In [15]:
da = da.sort_values('TEMPORARY_EMPLOYEE_ID')
da

       TEMPORARY_EMPLOYEE_ID                  EMPL_NM
36071                 100881      Lambert,Ronald Paul
26399                 101772  Heydinger,Beverly Jones
3184                  107118             Banaian,King
3185                  107118             Banaian,King
3186                  107118             Banaian,King
69496                 119394              Wendt,Jon R
69497                 119394              Wendt,Jon R
25809                 130878       Henderson,Peter VN
65151                 136323        Thompson,Merton E
65150                 136323        Thompson,Merton E
2970                  164439          Baker,Richard J
69282                 188199         Weisman,Robert A
56381                 195426          Salerno,Theresa
21848                 196317         Goslovich,Eric L
11870                 205128           Corey,George J
68364                 206019         Walker,William J
36285                 215820         Langen,William G
3493                  226413        Barriere,Robert L
15825                 267696           Dyer,William D
36157                 273141        Landers,Michael J
4948                  276705        Bergin,J Lawrence
50463                 297792         Pereira,Donald L
43843                 301356         Minchak,Martha J
67063                 302247                 Vang,Bee
57988                 308385        Schoenbaum,Mark F
60259                 309276           Sizer,Walter S
60258                 309276           Sizer,Walter S
37120                 311058          Leach,Marilyn M
54119                 319869          Reuter,Rill Ann
54118                 319869          Reuter,Rill Ann
...                      ...                      ...
53426              116112843        Ratz,Adam Timothy
25362              116113041   Hedlin,Sameh Elizabeth
58102              116113239   Schotzko,Ashley Taylor
30083              116113338           Johnson,Beth E
56203              116113734            Ryman,Sally J
25111              116113833    Hawkins,Arthur Stuart
8280               116113932           Budnick,Taylor
69883              116114130            Whipps,Robert
57093              116114229         Schaefer,Gregory
58311              116114328        Schueppert,Daniel
29703              116114526           Jensen,James P
41524              116114724             Mazurek,Alex
27707              116114823        Hopkins,Lisa Lynn
46783              116114922             Nguyen,Thu H
28560              116115120              Hussen,Deqa
22855              116115417               Guhl,Sarah
55943              116115714         Rundquist,Nathan
45066              116115813          Moua,Joanna Mai
27403              116115912       Hollins,Nicole Lyn
14355              116116308       Diekmann,Michael W
15938              116116605          Eaton,Kenneth L
32817              116117001        Kessler,Matthew P
51869              116117595         Pojar,Mariah Ann
39440              116118090           Lund,Kurt Dean
19350              116118288          Frazier,Emani F
39043              116118387                Lor,Lue X
8124               116118684            Bruss,Brenden
46211              116118981      Nelson,Jessica Lynn
52531              116120268         Prorok,Matthew P
14665              116122644  Dockter,Richard William

[73014 rows x 2 columns]

In [6]:
govdata2 = pd.read_excel(r'C:\Users\wc145\Desktop\fiscal-year-2015.xlsx',sheet_name='FY15_EARNINGS')

In [8]:
db = pd.DataFrame(govdata2,columns=['TEMPORARY_EMPLOYEE_ID','REGWAGES'])

In [21]:
dc = pd.merge(da, db, on='TEMPORARY_EMPLOYEE_ID', how='outer')

In [11]:
scrapedata = pd.read_excel(r'C:\Users\wc145\Desktop\Minnesota_Scrape\Openbook_2015.xlsx')

In [29]:
dd = pd.DataFrame(scrapedata,columns=['Name','Salary'])

In [ ]:
i = 0
for index1, row1 in dc.iterrows():
    for index2, row2 in dd.iterrows():
         if row1['EMPL_NM'] == row2['Name']:
                i = i+1
                print(i)
                print(row1['EMPL_NM'])
                break